;;; Automatically generated by ‘recentf’ on Sun Dec  8 10:53:47 2024.

(setq recentf-list
      '(
        "~/Nextcloud/SlidesQuimica/QO/Polimeros/Polimeros.org"
        "~/.emacs.d/var/treemacs/persist.org"
        "~/.config/awesome/rc.lua"
        "~/Nextcloud/AulasQuimica/main.org"
        "~/Nextcloud/SlidesQuimica/main.org"
        "~/Nextcloud/SlidesQuimica/extra.tex"
        "~/Nextcloud/SlidesQuimica/extra.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
