;;; Automatically generated by ‘recentf’ on Sat Dec  7 21:28:07 2024.

(setq recentf-list
      '(
        "~/.emacs.d/var/treemacs/persist.org"
        "~/Nextcloud/AulasQuimica/main.org"
        "~/Nextcloud/SlidesQuimica/extra.tex"
        "~/Nextcloud/SlidesQuimica/extra.org"
        "~/Nextcloud/SlidesQuimica/main.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
