;;; Automatically generated by ‘recentf’ on Sat Dec 14 06:13:30 2024.

(setq recentf-list
      '(
        "~/.emacs.d/var/treemacs/persist.org"
        "~/Nextcloud/SlidesQuimica/QG/Aula06.org"
        "~/Nextcloud/SlidesQuimica/QG/TabelaPeriodica/PropriedadesPeriodicas.org"
        "~/Nextcloud/SlidesQuimica/QG/TabelaPeriodica/Tabela.org"
        "~/Nextcloud/SlidesQuimica/QG/SeparacaoMisturas/SeparacaoMisturas.org"
        "~/Nextcloud/SlidesQuimica/QG/Estequiometria/CalculosEstequiometricosI.org"
        "~/Nextcloud/SlidesQuimica/main.org"
        "~/Nextcloud/SlidesQuimica/QO/Polimeros/Polimeros.org"
        "~/Nextcloud/AulasQuimica/main.org"
        "~/Nextcloud/AulasQuimica/Fisico_Quimica/Radioatividade/RadioatividadeII.org"
        "~/Nextcloud/AulasQuimica/Quimica_Geral/LeisPonderais/FormulaMinima.org"
        "~/Nextcloud/AulasQuimica/Quimica_Geral/LeisPonderais/LeiLavosier.org"
        "~/Nextcloud/SlidesQuimica/extra.tex"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
