;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(TeX-command-history file-name-history extended-command-history command-history minibuffer-history read-expression-history))
(setq TeX-command-history '("Other" "Biber"))
(setq file-name-history '("~/Nextcloud/SlidesQuimica/"))
(setq extended-command-history '("treemacs" "treemacs-edit-workspaces" "treemacs" "package-install" "treemacs"))
(setq command-history '((treemacs nil) (execute-extended-command nil "treemacs") (treemacs nil) (execute-extended-command nil "treemacs") (treemacs-edit-workspaces) (execute-extended-command nil "treemacs-edit-workspaces" "treemacs-e") (treemacs nil) (execute-extended-command nil "treemacs") (execute-extended-command nil "package-install" "pack") (treemacs nil) (execute-extended-command nil "treemacs") (treemacs nil) (execute-extended-command nil "treemacs") (treemacs nil) (execute-extended-command nil "treemacs" "tre") (evil-record-macro 32)))
(setq minibuffer-history '("lualatex" "Portuguese"))
(setq evil-jumps-history '((982 "/home/fabio/Nextcloud/AulasQuimica/Redacao/mainRedacao.tex")))
(setq projectile-project-command-history '#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()))
